version: '3.1'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: kiran
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: kiran
      MYSQL_PASSWORD: admin123
      MYSQL_RANDOM_ROOT_PASSWORD: sai#123
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
      - 33060

volumes:
  wordpress:
  db:
